'use server';

/**
 * @fileOverview AI-assisted recovery phrase generation flow.
 *
 * - generateRecoveryPhrase - Generates a recovery phrase for password reset.
 * - RecoveryPhraseInput - The input type for the generateRecoveryPhrase function.
 * - RecoveryPhraseOutput - The return type for the generateRecoveryPhrase function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const RecoveryPhraseInputSchema = z.object({
  userInfo: z
    .string()
    .describe(
      'Information about the user, including past interactions, preferences, and any available account details.'
    ),
});
export type RecoveryPhraseInput = z.infer<typeof RecoveryPhraseInputSchema>;

const RecoveryPhraseOutputSchema = z.object({
  recoveryPhrase: z
    .string()
    .describe(
      'A unique, memorable phrase generated by the AI for password recovery.'
    ),
  instructions: z
    .string()
    .describe(
      'Instructions for the user on how to use the recovery phrase to reset their password.'
    ),
});
export type RecoveryPhraseOutput = z.infer<typeof RecoveryPhraseOutputSchema>;

export async function generateRecoveryPhrase(
  input: RecoveryPhraseInput
): Promise<RecoveryPhraseOutput> {
  return recoveryPhraseFlow(input);
}

const prompt = ai.definePrompt({
  name: 'recoveryPhrasePrompt',
  input: {schema: RecoveryPhraseInputSchema},
  output: {schema: RecoveryPhraseOutputSchema},
  prompt: `You are an AI assistant designed to generate a unique and memorable recovery phrase for users who have forgotten their passwords.

  Based on the provided user information, create a recovery phrase that is easy to remember but difficult to guess. Also generate instructions for the user on how to use the recovery phrase to reset their password.

  User Information: {{{userInfo}}}
  `,
});

const recoveryPhraseFlow = ai.defineFlow(
  {
    name: 'recoveryPhraseFlow',
    inputSchema: RecoveryPhraseInputSchema,
    outputSchema: RecoveryPhraseOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
